spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/search_engine
    username: root
    password: Rfvhu1941.
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false

logging:
  level:
    org.springframework: ERROR
    searchengine: INFO


indexing-settings:
  sites:
    - url: http://radiomv.ru
      name: radiomv
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://skillbox.ru
      name: Skillbox
connection-settings:
  userAgent: Mozilla/5.0 (X11; Fedora;Linux x86; rv:60.0) Gecko/20100101 Firefox/60.0
  referer: https://www.google.com