# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: Rfvhu1941.
    driver-class-name: com.mysql.cj.jdbc.Driver
